version: '3.8'

services:
  web:
    build: .
    command: > 
      sh -c "python3 ./src/apps/users/commands/migrate.py && python3 ./src/app.py"
    volumes:
      - "./:/code"
    depends_on:
      - postgres
    networks:
      - acquaintance_internet
      - acquaintance_pg_net
  postgres:
    image: postgres
    ports:
      - "8888:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: "${PG_DBNAME}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    container_name: postgres-acquaintance
    volumes:
      - acquaintance_postgresql_data:/var/lib/postgresql/data/
    networks:
      - acquaintance_pg_net

volumes:
  acquaintance_postgresql_data: null

networks:
  acquaintance_internet:
    name: acquaintance_internet
    driver: bridge
  acquaintance_pg_net:
    name: acquaintance_pg_net
    driver: bridge